//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_pos_ferreteras
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_posEntities : DbContext
    {
        public db_posEntities()
            : base("name=db_posEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fact_estatus> fact_estatus { get; set; }
        public virtual DbSet<fact_tipo_fiscales> fact_tipo_fiscales { get; set; }
        public virtual DbSet<fact_tipo_rfc> fact_tipo_rfc { get; set; }
        public virtual DbSet<inf_contacto_fiscales> inf_contacto_fiscales { get; set; }
        public virtual DbSet<inf_empresa> inf_empresa { get; set; }
        public virtual DbSet<inf_fiscales> inf_fiscales { get; set; }
        public virtual DbSet<inf_sepomex> inf_sepomex { get; set; }
        public virtual DbSet<inf_usuarios> inf_usuarios { get; set; }
        public virtual DbSet<fact_tipo_usuarios> fact_tipo_usuarios { get; set; }
    }
}
